name: Docker Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  call-git-object-name-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-git-object-name.yml@v0.6.0

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@v0.6.0
    with:
      version_tag: ${{ needs.call-git-object-name-workflow.outputs.name }}
      release_branch: main
      develop_branch: dev
      user: ${{ github.actor }}
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
